const LearningData = {
  learningTitleText: 'Learning Plans',
  learningActivityTitleText: 'Learning Activities',
  learningCompetencyModelText: 'Competencies',
  learningPlanValidationMessageForAllBlankField: 'Error saving learning plans: ["Sales role must exist", "Name can\'t be blank", "Sales role can\'t be blank"]',
  learningActivityValidationMessageForAllBlankField: 'Error saving learning activity: ["Course must exist", "User must exist", "Course can\'t be blank", "User can\'t be blank"]',
  learningPlanValidationMessageForBlankSaleField: 'Error saving learning plans: ["Sales role must exist", "Sales role can\'t be blank"]',
  successMessageForNewLearning: 'Learning Plan was successfully created.',
  successMessageForDeleteLearning: 'Learning Plan was successfully destroyed.',
  successMessageForEditLearning: 'Learning plan was successfully updated.',
  allBlankFieldValidationMessageForNewLearningUserCollection: 'Error saving in learning user collection: ["User collection must exist", "User collection can\'t be blank", "Active date can\'t be blank", "Due date can\'t be blank"]',
  activeAndDueDateValidationMessageForNewLearningUserCollection: 'Error saving in learning user collection: ["Active date can\'t be blank", "Due date can\'t be blank"]',
  dueDateValidationMessageForNewLearningUserCollection: 'Error saving in learning user collection: ["Due date can\'t be blank"]',
  validationMessageWhenActiveDateIsGreaterThanDue: 'Error saving in learning user collection: ["Active date can\'t be greater than initial due date."]',
  invalidFeedbackMessageWhenActiveDateIsGreaterThanDue: 'can\'t be greater than initial due date.',
  successMessageForNewLearningUserCollection: 'Learning User Collection was successfully created.',
  successMessageForDeleteNewLearningUserCollection: 'Learning User Collection was successfully deleted.',
  updatedNewLearningUserCollectionSuccessMessage: 'Learning User Collection was successfully updated.',
  learningActivityAssignFieldValidation: 'Error saving learning activity: ["User must exist", "User can\'t be blank"]',
  learningActivityCourseFieldValidation: 'Error saving learning activity: ["Course must exist", "Course can\'t be blank"]',
  successMessageForNewLearningActivity: 'Learning Activity was successfully created.',
  successMessageForDeleteLearningActivity: 'successfully destroyed 1 Learning Activity',
  successMessageForEditLearningActivity: 'Learning Activity was successfully updated.',
  allBlankFieldValidationMessageForCourseCustomization: 'Error saving course: ["Name can\'t be blank", "Description can\'t be blank", "Planned duration can\'t be blank", "Planned duration is not a number", "Course type can\'t be blank"]',
  validationMessageForCourseTypeAndDescription: 'Error saving course: ["Description can\'t be blank", "Planned duration can\'t be blank", "Planned duration is not a number", "Course type can\'t be blank"]',
  validationMessageForDescriptionDurationAndScorm: 'Error saving course: ["Description can\'t be blank", "Planned duration can\'t be blank", "Planned duration is not a number", "Scorm can\'t be blank"]',
  validationMessageForDurationAndScrom:'Error saving course: ["Planned duration can\'t be blank", "Planned duration is not a number", "Scorm can\'t be blank"]',
  validationMessageForScrom: 'Error saving course: ["Scorm can\'t be blank"]',
  successMessageForCourse: 'Course was successfully created.',
  validationMessageForExistingScrom: 'Error saving course: ["Scorm has already been taken"]',
  successMessageForDeleteCourse: 'Course was successfully deleted.',
  successMessageForEditCourse: 'Course was successfully updated.',
  successMessageForCourseCompetency: 'Course Competency was successfully created.',
  allBlankFieldValidationMessageForCourseMapping: 'Error saving course competency: ["Competency must exist", "Competency can\'t be blank", "Passing score can\'t be blank", "Passing score is not a number", "Weight can\'t be blank", "Weight is not a number", "Either or both proficiency_level and lpac_level should be present."]',
  validationMessageForPassingScoreAndWeight: 'Error saving course competency: ["Passing score can\'t be blank", "Passing score is not a number", "Weight can\'t be blank", "Weight is not a number", "Either or both proficiency_level and lpac_level should be present."]',
  validationMessageForWeight: 'Error saving course competency: ["Weight can\'t be blank", "Weight is not a number"]',
  successMessageForEditCourseMapping: 'Course Competency was successfully updated.',
  sucessMessageForDeleteCourseMapping: 'Course Competency was successfully deleted.',
  sucessMessageForNewCourseTranslation: 'Course was successfully updated.',
  successMessageForDeleteCourseTranslation: 'Course translation was successfully deleted.',
};

// export the users you created so you can import them in your tests
export { LearningData};