const LearningPage = {
  learningPlanNameId: '#learning_plan_name',
  learningSalesRoleDropdownId: '#learningplan_user_group_select',
  learningPlanItemsSelectId: '#panel-learning-plan-items select.form-control',
  learningPlanItemsCheckboxId: '#select_all_learning_plan_item',
  learningRelativeOrderId: '#learning_plan_relative_order',
  newLearningUserCollectionActiveFieldId: '#learning_user_collection_active_date',
  newLearningUserCollectionDueDateFieldId: '#learning_user_collection_due_date',
  newLearningUserCollectionNameInTableId: '#learning_user_collection .table tbody td:nth-child(1) a',
  newLearningUserCollectionNameLinkId: '#learning_user_collection .table tbody tr td a',
  learningPlanCollapseArrowId: 'i.fa.fa-chevron-down.pull-right.collapse-arrow',
  learningPlanCompetenciesTableListId: 'tbody#learning-plan-sortable tr td:nth-child(1)',
  learningPlanCompetenciesCheckboxId: 'tbody#learning-plan-sortable tr td:nth-child(1) input[type="checkbox"]',
  learningCompetencyModelId: '#myModalLabel',
  learningCompetenciesCheckboxId: '#selected_',
  learningCompetenciesModelButtonId: '#myModelButton',
  learningActivityCourseFieldId: '#course_status_course_id',
  learningActivityUserFieldId: '#course_status_user_id',
  learningActivityStartDateId: '#course_status_start_date',
  learningActivitySubmittedDateId: '#course_status_submitted_date',
  learningActivityEndDateId: '#course_status_end_date',
  learningActivityScopeFieldId: '#course_status_score',
  learningActivityStatusId: '#course_status_status',
  learningActivityDeleteSelectedButtonId: '#annual a',
  courseNameId: '#course_name',
  courseTypeId: '#course_course_type',
  courseDescriptionId: '#course_description',
  courseHours: '#course_hours',
  courseMinutes: '#course_minutes',
  scormId: '#course_scorm_id',
  courseMappingDropdownId: '.form-group.row select',
  courseMappingPassingScoreId: '#course_competency_passing_score',
  courseMappingWeightId: '#course_competency_weighting_factor',
  courseTranslationLocaleId: '#course_locale',
};

// export the users you created so you can import them in your tests
export { LearningPage};