const SalesPage = {
	saleInputFieldId: '#sales_role_name',
	successMessageSales: 'div.alert-success',
	templateSelectId: '.form-group select',
	growthAlignedGoalDropdownIcon: 'a.expand-collapsed-btn i.fa.fa-chevron-down.pull-right',
	growthAlignedGoalNewButton: 'button.btn-success:nth-child(1)',
	growthAlignedGoalPopupTextId: '.modal-title span',
	metricId: '[name="metric_id"]',
	metricDisplayNameId: '#name',
	goalId: '#goal',
	metricNameInTableId: '#competency_metric_weighting table > tbody > tr > td:nth-child(1)',
	metricEditButton: '#competency_metric_weighting table > tbody > tr > td:nth-child(4) > button > i',
	competencyCheckboxesId: '.form-check .form-check-input.competency_user_group',
	strategicCheckboxesId: 'tr[role="row"] td:nth-child(4) .form-check-input',
	proficiencyLevelId: 'tr[role="row"] td:nth-child(5) .form-control',
	userCollectionButtonId: '#add_users_to_user_collection .card-body button',
	searchInputFieldAddUserPopupId: '.add-users-popup input[name="search_text"]',
	searchButtonAddUserPopupId: '.add-users-popup button .fa.fa-search',
	checkboxOnAddUserPopupId: '.add-users-popup .form-check-label',
	addSelectedUserButtonId: '.add-users-popup .btn.btn-success',
	successMessageForAddedSelectedUserId: '.alert.alert-success.alert-dismissible.fade.show',
	countOfSearchedUser: '.add-users-popup table tbody tr',
	closeUserPopup: '.add-users-popup .close',
	userCollectionRowId: '#add_users_to_user_collection table > tbody > tr',
	userCollectionCheckboxId: '#add_users_to_user_collection .tgrid-body-table input',
	successMessageUserSales: 'div.alert-success span',
	nameOfSelectedUserId: '#add_users_to_user_collection tr:nth-child(1) td[class="tgrid-data-cell"]:nth-child(2)',
	salesUserSearchFieldUId: 'input[name="search_text"]',
	blankFieldErrorId: '.error span',
	noSearchMessageId: '.table.table-striped.sortable tbody tr td center',
	noUserInUserGroupId: '#add_users_to_user_collection .text-center span',

};

export { SalesPage};