const UserPage = {
	accountNavDropdown: '#accountsNav li.nav-item.dropdown a.nav-link',
	dropdownMenuItem: '.dropdown-menu.dropdown-menu-right.show .dropdown-item',
	importUserButton: 'button[data-target="#import_users_modal_popup"]',
	selectButton: '#new_user .form-group.row select',
	unSelectButton: '.edit_user #user_collection_multi_select option',
	userFirstNameId: '#new_user #user_first_name',
	userLastNameId: '#new_user #user_last_name',
	userEmailId: '#user_email',
	newPasswordId: '#user_password',
	confirmPasswordId: '#user_password_confirmation',
	warningModelId: '.modal-title',
	modelFooterButtonId: '.modal-footer button',
	userSearchFieldId: 'input[name="search_text"]',
	userSearchButtonId: 'button span.fa.fa-search',
	userSearchCreteriaId: '.row .search-criteria-text',
	importUserButton: 'button[data-target="#import_users_modal_popup"]',
	modelFooterATagId: '.modal-content .modal-footer a',
	modelFooterCloseButtonId: '#account_users_import .modal-footer button',
	successMessageUser: 'div.alert-success',
	bulkEditUserButton: '#bulk_edit_users',
	allCheckBoxId: '#select_all',
	warningMessageIdOnBulkEditForm: 'span.modal-title',
	bulkEditFormCancelButtonId: '.modal-body button[class="btn btn-default"]',
	loginAsUserId: '.login-as-user-btn',
	loginAsUserNameOnTopId: '.top-strip-main p',
	licenseFieldId: '#account_licensed_users',
	navItemId: '.assess-tabs .nav-item',
	nextButtonId: 'button.btn.btn-primary',
	behaviourAnswerRadioButtonId: 'table td:nth-child(2) input',
	behaviourAnswerSubmitButtonId: 'button.btn.btn-primary',
	answerConfirmationId: '.modal-body',
	answerConfirmationCloseButtonId: '.modal-footer button',
	knowledgeAssessmentNextButtonId: 'button.btn.btn-primary',
	knowledgeAssessmentRadioButtonId: 'table tr:nth-child(2) td:nth-child(1) input',
	returnButtonId: 'input[type="submit"][value="Return"]',
	searchCaretDownId: '.input-group-append button span.fa.fa-caret-down',
	searchFieldReactSelctDropdownId:'.react-select__dropdown-indicator',
	textOnStrategicPageId: '.card .card-body .row .col-md-4',
	assessmentPeriodFieldIdOnStrategicPage: '.react-select__single-value',
	cursorPointerId: 'span.cursor-pointer',
	collapseReactSelectFieldId: '.custom-select-spc .react-select__value-container--is-multi',
	salesRoleInputReactSelect: '#react-select-3-input',
	userCollectionInputReactSelect: '#react-select-4-input',
	knowledgeAssessmentGraphId: '.highcharts-background',
	textIdOnKnowledgeAssessmentResult: '.highcharts-legend-item text tspan',
	competencyNameIdOnKnowledgeAssessmentResult: '.highcharts-axis-labels.highcharts-xaxis-labels span span',
	knowledgeAssessmentGraphFilterId: '.highcharts-legend-item',
	assignedAssessmentRowId: '#assigned-assessments table tbody tr',
	assessmentPdfFileId: '.fa.fa-file',
	passwordNoteId : '.text-muted',
	customDisableButtonId: '.custom-disable-btn a',
	sendInitialConfirmationEmailButtonId: 'a.send-initial-confirmation-btn',
	resendConfirmationEmailButtonId: 'a.bulk-resend-confirmation-btn',
	directReportTableId: '#direct-reports table tbody tr td a',
	userNameOnAssessPageId: 'ul.navbar-nav li:nth-child(2)',
	assessNavLinkId: 'a.assess.nav-link span',
	improveNavLinkId: 'a.improve.nav-link span',
	improveDisableNavLinkId: 'a.improve.nav-link',
	salesToolNavLinkId: 'a.sales-tools.nav-link span',
	salesToolNavAnchorId: 'a.sales-tools.nav-link',
	salesToolDisableNavLinkId: 'a.sales-tools.nav-link',
	accountAssessCheckboxId: '#account_account_feature_list_attributes_assess_module',
	accountImproveCheckboxId: '#account_account_feature_list_attributes_improve_module',
	accountSalesToolCheckboxId: '#account_account_feature_list_attributes_sales_tools_module',
	accountOverallTabId: '#account_account_feature_list_attributes_overall_page',
	accountStrategicTabId: '#account_account_feature_list_attributes_strategic_page',
	accountReportTabId: '#account_account_feature_list_attributes_reports_page',
	improveResultTabId: '#account_account_feature_list_attributes_improve_results_page',
	improveOverallProgressId: '#account_account_feature_list_attributes_overall_progress_page',
	improveAssignmentProgressTabId: '#account_account_feature_list_attributes_assignment_progress_page',
	improveTeamProgressTabId: '#account_account_feature_list_attributes_team_progress_page',
	improveMyLearningTabId: '#account_account_feature_list_attributes_my_learning_page',
	improveLearningLibraryTabId: '#account_account_feature_list_attributes_learning_library_page',
	improveConversionGeniusTabId: '#account_account_feature_list_attributes_conversation_genius_page',
	improveMyTeamAssessmentTabId: '#account_account_feature_list_attributes_my_team_assignments_page',
	saleToolsReportTabId: '#account_account_feature_list_attributes_sales_tool_results_page',
	saleToolsUsageTabId: '#account_account_feature_list_attributes_sales_tool_usage_page',
	saleToolOpportunitiesTabId: '#account_account_feature_list_attributes_opportunities_page',
	saleToolOpportunitiesId: '#account_account_feature_list_attributes_my_team_opportunities_page',
	saleToolAdminTabId: '#account_account_feature_list_attributes_admin_page',
	frontEndInformationMessageId: '.text-center span',
	assessNavTitleId: 'li.nav-title.assess',
	improveNavTitleId: 'li.nav-title.improve',
	assessTabOverallCheckboxId: '#account_account_feature_list_attributes_overall_page',
	assessTabStrategicTabCheckboxId: '#account_account_feature_list_attributes_strategic_page',
	assessTabReportCheckboxId: '#account_account_feature_list_attributes_reports_page',
	reportAnimatedFadeInId: '.animated.fadeIn span',
	reportWarningCardTitle: '.card-accent-warning.card span',
	reportSelectId: '.form-control',
	reportTreeTableId: '.reports-tree-table-container span',
	reportDropdownIcon: '.card-accent-warning.card i',
	assessmentReportsTitleId: '.card-accent-warning.card .d-flex.justify-space-between.align-items-center.toggle.card-header span',
	strategicLabelId: '.col-md-4 span',
	strategicCompetencyAssessmentResultId: '.row .col-10 span',
	strategicUserCountId: '.d-flex.float-right span',
	strategicKnowledgeAssessmentResultTextId: '.position-relative.card-header span',
	strategicIndividualResultTextId: 'div.mb-2.d-flex.align-items-center span',
	strategicResultTextId: '.card-accent-warning.card .toggle.card-header span',
	overallSalesRoleTextId: '.card-accent-warning.card .d-flex.justify-space-between.align-items-center.toggle.card-header .h4',
	overallRoleAverageTextId: '.col h5 span',
	overallCompetencyNameId: '.highcharts-container span',
	overallRoleAverageTextIdInGraph: '.highcharts-legend-item tspan',
	overallSelectFieldUserCollectionId: '.react-select__placeholder span',
	overallSearchFieldPlaceholderTextId: '.rc-tree-select-search__field__placeholder span',
	overallAssessmentPeriodDropdownId: '.custom-select-spc .react-select__single-value',
	overallUserCollectionDropdownId: '.custom-select-spc .react-select__placeholder',
	overallUserCollectionDropdownInputId: '.custom-select-spc .react-select__input #react-select-3-input',
	overallTerritoryDropdownId: '.custom-select-spc.territories-tree .rc-tree-select-search__field__placeholder',
	overallBusinessDropdownId: '.business-unit-tree .rc-tree-select-search__field__placeholder',
	enabledAccoutFeatureId: '#enable_ug_feature_control',
	noLearningTextActivityId: 'div:nth-child(3) > div > span',
	noLicensedContentTextId: 'div.collapse.show > div > span',
	coachQuizModeLabelId: '.custom-control-label',
	myTeamAssignmentTextId: 'div.display-5 > span',
	myTeamAssignmentContentId: '.card-accent-teal span',
	noAssignmentAssignId: '.collapse.show span',
	assignmentProgressHeaderTextId: '.card-header h5 span',
	organizationTableLabelId: '.card-body label.text-uppercase span',
	myTeamTableHeaderLabelId: '.table thead th span:nth-child(1)',
	myTeamTableUserNameLabelId: '.table tbody td a',
	assignmentProgressSelectionCountId: 'div[class*="select-spc"]',
	assignmentProgressPlaceholderId: 'div[class*="select-spc"] div[class$="placeholder"] span',
	resultsInfoId: '.card-body > span',
	resultField1Id: '#react-select-2-input',
	overallHelpTextId: '.help-text > span',
	overallHeaderLabelId: '.card-header .h4 span',
	overallMarkedLabelId: 'div[class^="custom-responsive"] > span',
	overallHeaderSectionId: '.card-header-actions span',
	overallProgressAxisLabelId: '.highcharts-xaxis-labels text',
	overallProgressTableActivityId: '.table>tbody>tr>td:nth-child(2)>center span',
	overallProgressActivityValueId: '.card-body div.text-center:nth-child(1) .h3',
	overallProgressTableNotStartedId: '.table>tbody>tr>td:nth-child(5)>center span',
	overallProgressNotStartedValueId: '.card-body div.text-center:nth-child(4) .h3',
	teamProgressLabelId: '.card-body h4 span',
	teamProgressLabel1Id: '.card-body h4 a',
	teamProgressBarId: '.progress-bar',
	myLearningActivityId: '.card .card-header h5',
	myLearningActivityFutureDateId: '.card .card-header div[class^="w"]>span>span>span',
	myLearningLessonId: '.panel-header a',
	myLearningLessonDateId: '.panel-header>div:nth-child(3)>div>span>span',
	assessorInTeamTableId: 'table a',
	validPainTextId: '.d-block.mt-4 p',
	painSecondaryButtonId: '.pain.btn.btn-secondary.btn-block',
	reasonSecondaryButtonId: '.reason.btn.btn-secondary.btn-block',
	tryAgainButtonId: 'button.btn.btn-primary',
	switchLabelId: '.custom-control-label',
	selectIndustryAndRole: '.btn.btn-secondary.btn-block',
	myteamManagerTextId: 'table tbody tr td:nth-child(10) span',
	myteamDirectReportTextId: 'table tbody tr td:nth-child(11) span',
	salesToolsResultTextId: '#sales-tools-results-page div span',
	usageTableHeaderId: '.table>thead>tr>th>span',
	myOpportunitieslabelId: '.opportunities-panel span',
	adminMenuLabelId: '.nav-pills a',
	adminTableHeaderId: '.table>thead>tr>th',
	adminDropdownLabelId: 'div.dropdown a',
	myOpportunitiesAddNewId: '//span[contains(text(),\'Add New\')]/ancestor::a',
	myOpportunitiesSaveButtonId: '//span[contains(text(),\'Save\')]/ancestor::button',
	myOpportunitiesErrorId: '.error span',
	myOpportunitiesNameId: 'input[name="name"]',
	myOpportunitiesStatusId: 'select[name="status"]',
	myOpportunitiesAccountNameId: 'input[name="accountName"]',
	myOpportunitiesEstimateRevenueId: 'input[name="estimateRevenue"]',
	myOpportunitiesExpectedDateId: 'input[name="expectedCloseDate"]',
	myOpportunitiesEditButtonId: '//span[contains(text(),\'Edit\')]/ancestor::button',
	myOpportunitiesDeleteButtonId: '//span[contains(text(),\'Delete\')]/ancestor::button',
	myOpportunitiesModalButtonId: '.modal-footer button',
	NewOpportunitiesCreatedTextId: '.opportunities-panel .row .col .pb-1 span:nth-child(2)',
	myOpportunitiesExisitingOppId: 'a.opp-main-heading',
	myOpportunitiesDetailsId: '.card-accent-opportunity',
	myOpportunitiesOtherDetailsTextId: '.btn-group .btn-light span',
	myOpportunitiesOtherDetailsLinkId: '.btn-group .btn-light',
	opportunitiesDetailsLabel1Id: '.card-accent-opportunity .card-header span',
	opportunitiesDetailsLabel2Id: '.card-accent-opportunity .add-more-text span',
	keyPlayersDetailsLabel1Id: '.key-players-panel .card-header span',
	keyPlayersDetailsLabel2Id: '.key-players-panel .add-more-text span',
	opportunitiesAddNewLinkId: '.add-more-text',
	keyPlayerValidationLabelId: '.text-danger span',
	keyPlayerTargetIndustryId: 'select[name="industryId"]',
	keyPlayerJobRoleId: 'select[name="jobRoleId"]',
	keyPlayerInformalRoleId: 'select[name="informalRole"]',
	keyPlayerPain1Id: '.key-player-pain-content .react-select__control',
	KeyPlayerPainInputId: 'input[id^="react-select"]',
	keyPlayerReason1Id: '.key-player-reason-panel-bottom .react-select__control',
	keyPlayerBackOpportunityId: '//span[contains(text(),\'Back to Opportunity\')]/ancestor::a',
	myOpportunityKeyPlayerLabelId: '.key-player-panel-row h6',
	myOpportunityKeyPlayerPainLabelId: '.key-player-panel-row ul li span.font-weight-bold',
	collaborationPlanAddNewId: '.add-more-text',
	collaborationPlanSaveActivityId: '.btn-primary',
	opportunitiesCancelButtonId: 'a.btn-default',
	collaborationPlanCancelId: '.btn-secondary',
	collaborationPlanModalButtonId: '.modal-dialog .modal-footer button',
	collaborationPlanModalHeaderTitleId: '.modal-dialog .modal-header .modal-title span',
	collaborationPlanModalMessageId: '.modal-dialog .modal-body span',
	collaborationPlanErrorMessId: '.text-danger span',
	collaborationPlanDeleteButtonId: '.delete-icon',
	collaborationPlanEventNameId: '.collaboration-event-name input',
	collaborationPlanResponsibleId: 'input[name="responsible"]',
	collaborationPlanResourcesId: 'input[name="resources"]',
	collaborationPlanDueDateId: 'input[name="dueDate"]',
	collaborationPlanAddNewDefaultFormId: '.col-plan-interview-panel',
	collaborationPlanCheckId: '.collaboration-plan-field-block',
	collaborationPlanExistingPlanId: '.col-plan-interview-panel',
	strengthSalesChecksSelectOptionId: '.card-accent-opportunity select',
	strengthSalesChecksLabel1Id: 'label[for="pain"] span',
	strengthSalesChecksLabel2Id: 'label[for="strengthValue"] span',
	strengthSalesChecksLabel3Id: 'label[for="power"] span',
	strengthSalesChecksLabel4Id: 'label[for="collaborate"] span',
	strengthSalesChecksLabel5Id: 'label[for="vision"] span',
	strengthSalesChecksLabel6Id: 'label[for="crta"] span',
	strengthSalesChecksCancelButtonId: '//span[contains(text(),\'Cancel\')]/ancestor::a',
	strengthSalesCheckDateId: 'text[text-anchor="start"] tspan',
	strengthSalesChecksItemId: '.sales-checks-panel-row a',
	strengthSalesChecksCreatedDetailsId: 'div.sales-checks-panel-row span > span',
	keyPlayersDetailsTxtId: '.kp-details-row > div:nth-child(2)',
	keyPlayersPainDetailsTxtId: '.key-player-pain-card>div>div>div>span:nth-child(2)',
	keyPlayersReasonQuestionId: '.questions-block',
	keyPlayersPainAnchorId: '.key-player-panel-row a',
	keyPlayerEditId: 'a[href$="/edit"]',
	keyPlayerEditHeaderId: '.key-player-panel .card-header span',
	lettersTitleLabel1Id: 'div[class*="light-blue"] .card-header span',
	lettersTitleLabel2Id: '.key-player-letters-panel .add-more-text span',
	lettersErrorLabelId: '.error span',
	lettersTemplateId: 'select[name="templateId"]',
	lettersCreatedLabelId: '.key-player-letters-panel .letter-row a',
	lettersDeleteButtonId: 'button.btn-danger',
};
export { UserPage};
